package ca.ulaval.glo4002.game.domain.actions;

public enum ActionEnumPriority {
    UPDATE_HAMSTAGRAM_ACCOUNTS_NEXT_TURN,
    MOVIES_PAY_CHARACTERS,
    APPLY_MOVIE_BONUS,
    HAMSTERS_PAY_REPRESENTED_BY,
    PAY_LAWYERS,
    UPDATE_CHARACTERS_NEXT_TURN,
    RESOLVE_LAWSUITS,
    FIND_LAWYER,
    CHARACTER_ACTION,
    ELIMINATE_CHARACTERS,
    RATTEDIN_REQUEST,
    CREATE_MOVIE,
    CREATE_CHARACTER,
    CHINCHILLA_SEND_HAMSTAGRAM_REQUESTS,
    HAMSTER_CHOOSE_BEST_HAMSTAGRAM_REQUEST,
    UPDATE_MOVIES_NEXT_TURN;

    public int getPriority() {
        return ordinal();
    }
}
